### ISSUE TITLE
Question about nested kernel API.

### ISSUE THREAD

**Issue by targetnull** [nestedkernel/PerspicuOS#3]
Hi, 

I am trying to understand the code based on your excellent paper. However, the APIs declared in the paper(nk_declare, nk_alloc, etc.) seem not to be called by the kernel? For example, I search the function `pt_update_is_valid`, ~~and the result shows that it appears only once(in [nk/lib/mmu.c#.L259](https://github.com/nestedkernel/PerspicuOS/blob/2ad54f8459e74bf1d45011d0e17075849b128952/nk/lib/mmu.c#.L259)), it is not even referenced~~.
----- Update: Sorry for my mistake before, the github default search functionality seems not good enough, `pt_update_is_valid` is referenced in the `__update_mapping` function.

I compared the difference between `FreeBSD9` and `FreeBSD9-orig` directory, trying to find out the modification. I find two possible functions in [FreeBSD9/sys/kern/kern_sva.c](https://github.com/nestedkernel/PerspicuOS/blob/2ad54f8459e74bf1d45011d0e17075849b128952/FreeBSD9/sys/kern/kern_sva.c), `provideSVAMemory` and `releaseSVAMemory`, both of which are referenced in the nk lib. However, the first line of `provideSVAMemory` is `panic("Don't call this!");`!

Now I'm a little confused, where and how is the nk library being used? Did I miss anything?

Thanks.

**Comment by ndauten** [comment]
Hi @targetnull,

Unfortunately, the names in the implementation do not match the names from the paper. This implementation uses a similar but different system. Either way, the naming convention was kept consistent. 

The sva_* functions are nested kernel function calls. Doing a grep for those in the source should yield all the calls into the nested kernel. 

Are you just doing some exploratory reading? Please let me know if you have any specific questions. 

Best,
::Nathan::

**Comment by targetnull** [comment]
Hi, @ndauten 

Thanks for your reply, I'll look into those functions.

Yes, I'm doing exploratory reading. Actually, I want to implement something similar in Linux to protect specific modules as my graduation project. So I think I should understand how you do it first since I'm not very familiar with it, when to set the page table permission and so on.

Thanks again.

**Comment by ndauten** [comment]
@targetnull: please keep me posted on your questions and progress. I would love for you to contribute to the system and overall set of Nested Kernel implementations and use cases. I'm very interested in such directions. Please let me know if you have any ideas. Is there a way to PM in Github?

I have an IRC channel up for the nested kernel: #perspicuos on OFTC, but do not always check it. I'm up for suggestions on DM type discussions.

**Comment by targetnull** [comment]
@ndauten I'm glad that you are interested in it. AFAIK, there is currently no way to send private message in github(i guess that's what you mean). You can reach me by email whenever you want, my email is yzh07137@hotmail.com.
I'm preparing for an exam and other experiments recently, so I think I'll have to wait for a few weeks before I can commit myself to the project.
I'll keep you posted on lastest questions and progress. Thank you for your attention.

**Comment by ndauten** [comment]
@targetnull sounds great! Good luck.
