### ISSUE TITLE
try to run your source code in a FreeBSD9.0 on vmware

### ISSUE THREAD

**Issue by Rexliang** [nestedkernel/PerspicuOS#4]

**Comment by Rexliang** [comment]
Hello,I wanted to do some small research based on your Great work,and I tried many times to configure your code so I can at least run nested kernel.
But,to some unknown reason,there's something wrong.I'm new to freebsd,i don't known where.

That's what I do:
0.use the iso given in README.ME and install it on vmware,and give it 2GB RAM,a one-core CPU.
1.update 9.0 to 9.1-release, for there is a bug in Freebsd9.0,and I believe this is the only way.
2.switch an 9.0-Release kernel.
3.use gmake to install llvm of given version in source code.
4.modify /etc/make.conf to use the new clang
5.cd /nk,make
6.modify /etc/src.conf as README.md says.
7.cd /FreeBSD9,make buildkernel KERNCONF=NK -DNO_KERNELCLEAN -DNO_KERNELCONFIG -DNO_KERNELDEPEND -DNO_KERNELOBJ
8.make installkernel KERNCONF=NK INSTKERNNAME=per
9.reboot,and I got a SVA panic
![image](https://cloud.githubusercontent.com/assets/15193334/23327664/ebee358a-fb4a-11e6-8d3a-d57cfba2fdb2.png)
You see,this maybe too hard too me...Maybe I should try to use a real computer?Or I did something wrong?Could you help me out?This is important to me.Thank you very much.

**Comment by SleepyToDeath** [comment]
This panic warns you that a page table is not declared with the standard interface. On possibility is that it's a page table built during initialization, which must be handled manually. So, any modification to the kernel (e.g., upgrade from 9.0 to 9.1) could possibly introduce new unhandled init page table and cause a panic.

BTW, you can debug this manually. Just locate the problematic page table and set its descriptor to page table in nk.

Oh, I'm just a user. If it doesn't work, please wait for the developer......

**Comment by Rexliang** [comment]
@SleepyToDeath Thanks a lot. After reading your comment, I realized that the nested kernel source code should be good and I may did something wrong during the installation, and I assume it's not caused by using the vmware.
so I check my experiment log and perivous experiment VMs(cloned for backup), and here is what I found:
There's a time i don't know the /llvm in source code is useful and I just use the unmodified clang to make kernel, and the kernel installed has the same error(Panic:SVA:MMU:). And guess what,the bug I thought unsolvable in 9.0 seems not exists,the VMs version is FreeBSD9.0.
As i know,clang is just a frontend,but the llvm seems do the job of binary elimination,and this shouldn't be done by clang.
So,this is my thought：Maybe i just misconfigure the /etc/src.conf or the /etc/make.conf? I know it sounds stupid but it's possible,especially happens to a newbee like me.
So,would you do me a favor that paste your src.conf and make.conf? The bug confuse me a lot and i really need help. Thank you.

**Comment by SleepyToDeath** [comment]
@Rexliang Sorry but I no longer have access to the machine with the image I used. I guess you can use the ruby script they provide. As long as you can compile and install, I don't think it's a problem of configuration. Have you tried not to upgrade from 9.0 to 9.1?

**Comment by Rexliang** [comment]
@SleepyToDeath Ah,not my day.But thank you for your help.
Yes,I read the script and tried to install according to it,maybe I should try it,i'll consider about it.
And yes,the old version platform I just mentioned is 9.0, it installed nested kernel and has the same error.I looked up my experiment log and i'm sure about it. Can't remember when i did this.
So..the problem seems have two possible reasons:configuration or change of page tables. I'll try to solve this.If there is any progress,i will let you know.
Anyway,thank you very much,you help me a lot.Have a good day.

**Comment by ndauten** [comment]
@Rexliang thanks for your interest and sorry for the delayed response. It appears as though the problem is with updating the page tables. If you were using 9.1 then I would say there is some more porting to be done. But your kernel configuration could have uncovered page table modifications that we did not get in our version. This is the most likely candidate. I would be interested if you could reply back with the faulting function? This would let us know where it is, but I'm pretty sure it will be due to a missed update. 

We are also working on porting the implementation to FreeBSD 9.3, which is still under development.

**Comment by Rexliang** [comment]
@ndauten Thank you for your attention.I just report an error of "sva_load_cr4" by gmail and you have replied.Let me explain what happened after this SVA Panic.

1.After the SVA panic happened,I thought it might be the vmware? So I use a computer to do experiment.As you can see in the email,the kernel trap 9 happened,caused by sva_load_cr4.

2.I configured BIOS,when I disabled the Intel XD(execute disable) support,the kernel trap 9 happened again,but caused by sva_load_msr. below is the information:

Stopped at sva_load_msr+0x20:wrmsr
db>trace
Tracing pid 0 tid 0 td 0xffffffff8d0ca1c0
sva_load_msr() at sva_load_msr+0x20
btext() at btext+0x24

3.I know it‘s hard for me, and I gave up. Yesterday I use my own computer(another computer) to run the same vmware images I use before, and a strange thing happened: the SVA Panic disappeared,can't be reproduced by any image, any kernel I compiled. and the trap 9 happened. I swear that nothing happened to the images except I migrated them to my own computer, I just don't know what happened.

So...I'm glad to help, but the SVA panic seems disappeared, the printscreen above might be the only clue I can provide for you, I'm sorry for that. Wish my experience could help you a little.
I have to say, the freebsd9.1 seems to be the reason, but freebsd9.0 has a bug which make gmake can't be installed. The bug Undefined symbol “_ThreadRuneLocale”, if anybody see this comment has overcame it, please let me know.
Thank you for your help, and have a good day.

**Comment by ndauten** [comment]
Thanks @Rexliang. The error above is due to a page being used that has not been registered, and requires porting. This is likely due to using 9.1. 

The other errors are caused due to lack of hardware support for the features. If you look at the lines of code mentioned, they don't check for hardware features. So if you try to use them they will cause GP faults. 

Ultimately, you need SMEP and NX support enabled. 

Good luck in your exploration.
